---
name: Clean
description: A Github Action to clean the workspace on a self-hosted runner
runs:
  using: docker
  image: Dockerfile
inputs:
  service_ids:
    required: false
    default: ${{ toJSON(job.services.*.id) }}
